// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'

    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
// import 'firebase_options.dart';
// await Firebase.initializeApp(
// options: DefaultFirebaseOptions.currentPlatform,
// / );
/// ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiGCZxJO5pM7KpQh9I-BvOHjS6cEaBn2Q',
    appId: '1:152407953418:web:a49d7d92b97603e2efcff3',
    messagingSenderId: '152407953418',
    projectId: 'ticketing-flutter-one',
    authDomain: 'ticketing-flutter-one.firebaseapp.com',
    storageBucket: 'ticketing-flutter-one.appspot.com',
    measurementId: 'G-FE134SQNVD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZwWUVEzj69sDj3DxouskzWZSd4BKMK9c',
    appId: '1:152407953418:android:a6f37ed62b0127e8efcff3',
    messagingSenderId: '152407953418',
    projectId: 'ticketing-flutter-one',
    storageBucket: 'ticketing-flutter-one.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVUb-aHQQ4saNvVppB1bKwAO90WjCjbUU',
    appId: '1:152407953418:ios:202b1b3c1831f9f7efcff3',
    messagingSenderId: '152407953418',
    projectId: 'ticketing-flutter-one',
    storageBucket: 'ticketing-flutter-one.appspot.com',
    iosBundleId: 'com.example.ticketing',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVUb-aHQQ4saNvVppB1bKwAO90WjCjbUU',
    appId: '1:152407953418:ios:202b1b3c1831f9f7efcff3',
    messagingSenderId: '152407953418',
    projectId: 'ticketing-flutter-one',
    storageBucket: 'ticketing-flutter-one.appspot.com',
    iosBundleId: 'com.example.ticketing',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBiGCZxJO5pM7KpQh9I-BvOHjS6cEaBn2Q',
    appId: '1:152407953418:web:b9dde703e04bce10efcff3',
    messagingSenderId: '152407953418',
    projectId: 'ticketing-flutter-one',
    authDomain: 'ticketing-flutter-one.firebaseapp.com',
    storageBucket: 'ticketing-flutter-one.appspot.com',
    measurementId: 'G-TRGB36N5KX',
  );

  
}